package com.goodsoft.hotel.domain.entity.restaurantReservation;

/**
 * Created by duyuxiang on 2017/11/24.
 * 餐饮宴会预订
 */
public class YanhuiReservation {
    private String id;
    private String customerType;
    private String customerName;
    private String entryDate;
    private String peopleNumber;
    private String salesManager;
    private String contacts;
    private String contactsNumber;
    private String appointmentLength;
    private String attheTime;
    private String endDate;
    private String memberCard;
    private String contractUnit;
    private String corporateName;
    private String seatsNum;
    private String winePosition;
    private String isbilling;
    private String floatNum;
    private String invitationNum;
    private String paymentMethod;
    private String cancellationReasons;
    private String authorizedPerson;
    private String openTime;
    private String activity;
    private String validSignature;
    private String place;
    private String guaranteeNumber;
    private String tableType;
    private String electronicScreenContent;
    private String venueLayout1;
    private String venueLayout2;
    private String paymentInstructions1;
    private String paymentInstructions2;
    private String paymentInstructions3;
    private String otherEquirements;
    private String engineeringDpartment1;
    private String engineeringEpartment2;
    private String securityEpartment1;
    private String securityEpartment2;
    private String financeEpartment1;
    private String financeEpartment2;
    private String reception1;
    private String reception2;
    private String keepingDpartment1;
    private String keepingDpartment2;
    private String remarks;
    private String state;


    @Override
    public String toString() {
        return "YanhuiReservation{" +
                "id='" + id + '\'' +
                ", customerType='" + customerType + '\'' +
                ", customerName='" + customerName + '\'' +
                ", entryDate='" + entryDate + '\'' +
                ", peopleNumber=" + peopleNumber +
                ", salesManager='" + salesManager + '\'' +
                ", contacts='" + contacts + '\'' +
                ", contactsNumber='" + contactsNumber + '\'' +
                ", appointmentLength='" + appointmentLength + '\'' +
                ", attheTime='" + attheTime + '\'' +
                ", endDate='" + endDate + '\'' +
                ", memberCard='" + memberCard + '\'' +
                ", contractUnit='" + contractUnit + '\'' +
                ", corporateName='" + corporateName + '\'' +
                ", seatsNum='" + seatsNum + '\'' +
                ", winePosition='" + winePosition + '\'' +
                ", isbilling='" + isbilling + '\'' +
                ", floatNum=" + floatNum +
                ", invitationNum=" + invitationNum +
                ", paymentMethod='" + paymentMethod + '\'' +
                ", cancellationReasons='" + cancellationReasons + '\'' +
                ", authorizedPerson='" + authorizedPerson + '\'' +
                ", openTime='" + openTime + '\'' +
                ", activity='" + activity + '\'' +
                ", validSignature='" + validSignature + '\'' +
                ", place='" + place + '\'' +
                ", guaranteeNumber='" + guaranteeNumber + '\'' +
                ", tableType='" + tableType + '\'' +
                ", electronicScreenContent='" + electronicScreenContent + '\'' +
                ", venueLayout1='" + venueLayout1 + '\'' +
                ", venueLayout2='" + venueLayout2 + '\'' +
                ", paymentInstructions1='" + paymentInstructions1 + '\'' +
                ", paymentInstructions2='" + paymentInstructions2 + '\'' +
                ", paymentInstructions3='" + paymentInstructions3 + '\'' +
                ", otherEquirements='" + otherEquirements + '\'' +
                ", engineeringDpartment1='" + engineeringDpartment1 + '\'' +
                ", engineeringEpartment2='" + engineeringEpartment2 + '\'' +
                ", securityEpartment1='" + securityEpartment1 + '\'' +
                ", securityEpartment2='" + securityEpartment2 + '\'' +
                ", financeEpartment1='" + financeEpartment1 + '\'' +
                ", financeEpartment2='" + financeEpartment2 + '\'' +
                ", reception1='" + reception1 + '\'' +
                ", reception2='" + reception2 + '\'' +
                ", keepingDpartment1='" + keepingDpartment1 + '\'' +
                ", keepingDpartment2='" + keepingDpartment2 + '\'' +
                ", remarks='" + remarks + '\'' +
                ", state='" + state + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.ID
     *
     * @return the value of gs_yanhui_reservation.ID
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.ID
     *
     * @param id the value for gs_yanhui_reservation.ID
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.CUSTOMER_TYPE
     *
     * @return the value of gs_yanhui_reservation.CUSTOMER_TYPE
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.CUSTOMER_TYPE
     *
     * @param customerType the value for gs_yanhui_reservation.CUSTOMER_TYPE
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setCustomerType(String customerType) {
        this.customerType = customerType == null ? null : customerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.CUSTOMER_NAME
     *
     * @return the value of gs_yanhui_reservation.CUSTOMER_NAME
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.CUSTOMER_NAME
     *
     * @param customerName the value for gs_yanhui_reservation.CUSTOMER_NAME
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.ENTRY_DATE
     *
     * @return the value of gs_yanhui_reservation.ENTRY_DATE
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.ENTRY_DATE
     *
     * @param entryDate the value for gs_yanhui_reservation.ENTRY_DATE
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setEntryDate(String entryDate) {
        this.entryDate = entryDate == null ? null : entryDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.PEOPLE_NUMBER
     *
     * @return the value of gs_yanhui_reservation.PEOPLE_NUMBER
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getPeopleNumber() {
        return peopleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.PEOPLE_NUMBER
     *
     * @param peopleNumber the value for gs_yanhui_reservation.PEOPLE_NUMBER
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setPeopleNumber(String peopleNumber) {
        this.peopleNumber = peopleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.SALES_MANAGER
     *
     * @return the value of gs_yanhui_reservation.SALES_MANAGER
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getSalesManager() {
        return salesManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.SALES_MANAGER
     *
     * @param salesManager the value for gs_yanhui_reservation.SALES_MANAGER
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setSalesManager(String salesManager) {
        this.salesManager = salesManager == null ? null : salesManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.CONTACTS
     *
     * @return the value of gs_yanhui_reservation.CONTACTS
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.CONTACTS
     *
     * @param contacts the value for gs_yanhui_reservation.CONTACTS
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.CONTACTS_NUMBER
     *
     * @return the value of gs_yanhui_reservation.CONTACTS_NUMBER
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getContactsNumber() {
        return contactsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.CONTACTS_NUMBER
     *
     * @param contactsNumber the value for gs_yanhui_reservation.CONTACTS_NUMBER
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setContactsNumber(String contactsNumber) {
        this.contactsNumber = contactsNumber == null ? null : contactsNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.APPOINTMENT_LENGTH
     *
     * @return the value of gs_yanhui_reservation.APPOINTMENT_LENGTH
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getAppointmentLength() {
        return appointmentLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.APPOINTMENT_LENGTH
     *
     * @param appointmentLength the value for gs_yanhui_reservation.APPOINTMENT_LENGTH
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setAppointmentLength(String appointmentLength) {
        this.appointmentLength = appointmentLength == null ? null : appointmentLength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.ATTHE_TIME
     *
     * @return the value of gs_yanhui_reservation.ATTHE_TIME
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getAttheTime() {
        return attheTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.ATTHE_TIME
     *
     * @param attheTime the value for gs_yanhui_reservation.ATTHE_TIME
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setAttheTime(String attheTime) {
        this.attheTime = attheTime == null ? null : attheTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.END_DATE
     *
     * @return the value of gs_yanhui_reservation.END_DATE
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.END_DATE
     *
     * @param endDate the value for gs_yanhui_reservation.END_DATE
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.MEMBER_CARD
     *
     * @return the value of gs_yanhui_reservation.MEMBER_CARD
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getMemberCard() {
        return memberCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.MEMBER_CARD
     *
     * @param memberCard the value for gs_yanhui_reservation.MEMBER_CARD
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setMemberCard(String memberCard) {
        this.memberCard = memberCard == null ? null : memberCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.CONTRACT_UNIT
     *
     * @return the value of gs_yanhui_reservation.CONTRACT_UNIT
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getContractUnit() {
        return contractUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.CONTRACT_UNIT
     *
     * @param contractUnit the value for gs_yanhui_reservation.CONTRACT_UNIT
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setContractUnit(String contractUnit) {
        this.contractUnit = contractUnit == null ? null : contractUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.CORPORATE_NAME
     *
     * @return the value of gs_yanhui_reservation.CORPORATE_NAME
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getCorporateName() {
        return corporateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.CORPORATE_NAME
     *
     * @param corporateName the value for gs_yanhui_reservation.CORPORATE_NAME
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setCorporateName(String corporateName) {
        this.corporateName = corporateName == null ? null : corporateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.SEATS_NUM
     *
     * @return the value of gs_yanhui_reservation.SEATS_NUM
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getSeatsNum() {
        return seatsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.SEATS_NUM
     *
     * @param seatsNum the value for gs_yanhui_reservation.SEATS_NUM
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setSeatsNum(String seatsNum) {
        this.seatsNum = seatsNum == null ? null : seatsNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.WINE_POSITION
     *
     * @return the value of gs_yanhui_reservation.WINE_POSITION
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getWinePosition() {
        return winePosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.WINE_POSITION
     *
     * @param winePosition the value for gs_yanhui_reservation.WINE_POSITION
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setWinePosition(String winePosition) {
        this.winePosition = winePosition == null ? null : winePosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.ISBILLING
     *
     * @return the value of gs_yanhui_reservation.ISBILLING
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getIsbilling() {
        return isbilling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.ISBILLING
     *
     * @param isbilling the value for gs_yanhui_reservation.ISBILLING
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setIsbilling(String isbilling) {
        this.isbilling = isbilling == null ? null : isbilling.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.FLOAT_NUM
     *
     * @return the value of gs_yanhui_reservation.FLOAT_NUM
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getFloatNum() {
        return floatNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.FLOAT_NUM
     *
     * @param floatNum the value for gs_yanhui_reservation.FLOAT_NUM
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setFloatNum(String floatNum) {
        this.floatNum = floatNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.INVITATION_NUM
     *
     * @return the value of gs_yanhui_reservation.INVITATION_NUM
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getInvitationNum() {
        return invitationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.INVITATION_NUM
     *
     * @param invitationNum the value for gs_yanhui_reservation.INVITATION_NUM
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setInvitationNum(String invitationNum) {
        this.invitationNum = invitationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.PAYMENT_METHOD
     *
     * @return the value of gs_yanhui_reservation.PAYMENT_METHOD
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.PAYMENT_METHOD
     *
     * @param paymentMethod the value for gs_yanhui_reservation.PAYMENT_METHOD
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod == null ? null : paymentMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.CANCELLATION_REASONS
     *
     * @return the value of gs_yanhui_reservation.CANCELLATION_REASONS
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getCancellationReasons() {
        return cancellationReasons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.CANCELLATION_REASONS
     *
     * @param cancellationReasons the value for gs_yanhui_reservation.CANCELLATION_REASONS
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setCancellationReasons(String cancellationReasons) {
        this.cancellationReasons = cancellationReasons == null ? null : cancellationReasons.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.AUTHORIZED_PERSON
     *
     * @return the value of gs_yanhui_reservation.AUTHORIZED_PERSON
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getAuthorizedPerson() {
        return authorizedPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.AUTHORIZED_PERSON
     *
     * @param authorizedPerson the value for gs_yanhui_reservation.AUTHORIZED_PERSON
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setAuthorizedPerson(String authorizedPerson) {
        this.authorizedPerson = authorizedPerson == null ? null : authorizedPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.OPEN_TIME
     *
     * @return the value of gs_yanhui_reservation.OPEN_TIME
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.OPEN_TIME
     *
     * @param openTime the value for gs_yanhui_reservation.OPEN_TIME
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setOpenTime(String openTime) {
        this.openTime = openTime == null ? null : openTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.ACTIVITY
     *
     * @return the value of gs_yanhui_reservation.ACTIVITY
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getActivity() {
        return activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.ACTIVITY
     *
     * @param activity the value for gs_yanhui_reservation.ACTIVITY
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setActivity(String activity) {
        this.activity = activity == null ? null : activity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.VALID_SIGNATURE
     *
     * @return the value of gs_yanhui_reservation.VALID_SIGNATURE
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getValidSignature() {
        return validSignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.VALID_SIGNATURE
     *
     * @param validSignature the value for gs_yanhui_reservation.VALID_SIGNATURE
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setValidSignature(String validSignature) {
        this.validSignature = validSignature == null ? null : validSignature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.PLACE
     *
     * @return the value of gs_yanhui_reservation.PLACE
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.PLACE
     *
     * @param place the value for gs_yanhui_reservation.PLACE
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.GUARANTEE_NUMBER
     *
     * @return the value of gs_yanhui_reservation.GUARANTEE_NUMBER
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getGuaranteeNumber() {
        return guaranteeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.GUARANTEE_NUMBER
     *
     * @param guaranteeNumber the value for gs_yanhui_reservation.GUARANTEE_NUMBER
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setGuaranteeNumber(String guaranteeNumber) {
        this.guaranteeNumber = guaranteeNumber == null ? null : guaranteeNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.TABLE_TYPE
     *
     * @return the value of gs_yanhui_reservation.TABLE_TYPE
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getTableType() {
        return tableType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.TABLE_TYPE
     *
     * @param tableType the value for gs_yanhui_reservation.TABLE_TYPE
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setTableType(String tableType) {
        this.tableType = tableType == null ? null : tableType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.ELECTRONIC_SCREEN_CONTENT
     *
     * @return the value of gs_yanhui_reservation.ELECTRONIC_SCREEN_CONTENT
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getElectronicScreenContent() {
        return electronicScreenContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.ELECTRONIC_SCREEN_CONTENT
     *
     * @param electronicScreenContent the value for gs_yanhui_reservation.ELECTRONIC_SCREEN_CONTENT
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setElectronicScreenContent(String electronicScreenContent) {
        this.electronicScreenContent = electronicScreenContent == null ? null : electronicScreenContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.VENUE_LAYOUT_1
     *
     * @return the value of gs_yanhui_reservation.VENUE_LAYOUT_1
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getVenueLayout1() {
        return venueLayout1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.VENUE_LAYOUT_1
     *
     * @param venueLayout1 the value for gs_yanhui_reservation.VENUE_LAYOUT_1
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setVenueLayout1(String venueLayout1) {
        this.venueLayout1 = venueLayout1 == null ? null : venueLayout1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.VENUE_LAYOUT_2
     *
     * @return the value of gs_yanhui_reservation.VENUE_LAYOUT_2
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getVenueLayout2() {
        return venueLayout2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.VENUE_LAYOUT_2
     *
     * @param venueLayout2 the value for gs_yanhui_reservation.VENUE_LAYOUT_2
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setVenueLayout2(String venueLayout2) {
        this.venueLayout2 = venueLayout2 == null ? null : venueLayout2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.PAYMENT_INSTRUCTIONS_1
     *
     * @return the value of gs_yanhui_reservation.PAYMENT_INSTRUCTIONS_1
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getPaymentInstructions1() {
        return paymentInstructions1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.PAYMENT_INSTRUCTIONS_1
     *
     * @param paymentInstructions1 the value for gs_yanhui_reservation.PAYMENT_INSTRUCTIONS_1
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setPaymentInstructions1(String paymentInstructions1) {
        this.paymentInstructions1 = paymentInstructions1 == null ? null : paymentInstructions1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.PAYMENT_INSTRUCTIONS_2
     *
     * @return the value of gs_yanhui_reservation.PAYMENT_INSTRUCTIONS_2
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getPaymentInstructions2() {
        return paymentInstructions2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.PAYMENT_INSTRUCTIONS_2
     *
     * @param paymentInstructions2 the value for gs_yanhui_reservation.PAYMENT_INSTRUCTIONS_2
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setPaymentInstructions2(String paymentInstructions2) {
        this.paymentInstructions2 = paymentInstructions2 == null ? null : paymentInstructions2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.PAYMENT_INSTRUCTIONS_3
     *
     * @return the value of gs_yanhui_reservation.PAYMENT_INSTRUCTIONS_3
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getPaymentInstructions3() {
        return paymentInstructions3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.PAYMENT_INSTRUCTIONS_3
     *
     * @param paymentInstructions3 the value for gs_yanhui_reservation.PAYMENT_INSTRUCTIONS_3
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setPaymentInstructions3(String paymentInstructions3) {
        this.paymentInstructions3 = paymentInstructions3 == null ? null : paymentInstructions3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.OTHER_EQUIREMENTS
     *
     * @return the value of gs_yanhui_reservation.OTHER_EQUIREMENTS
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getOtherEquirements() {
        return otherEquirements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.OTHER_EQUIREMENTS
     *
     * @param otherEquirements the value for gs_yanhui_reservation.OTHER_EQUIREMENTS
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setOtherEquirements(String otherEquirements) {
        this.otherEquirements = otherEquirements == null ? null : otherEquirements.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.ENGINEERING_DPARTMENT_1
     *
     * @return the value of gs_yanhui_reservation.ENGINEERING_DPARTMENT_1
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getEngineeringDpartment1() {
        return engineeringDpartment1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.ENGINEERING_DPARTMENT_1
     *
     * @param engineeringDpartment1 the value for gs_yanhui_reservation.ENGINEERING_DPARTMENT_1
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setEngineeringDpartment1(String engineeringDpartment1) {
        this.engineeringDpartment1 = engineeringDpartment1 == null ? null : engineeringDpartment1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.ENGINEERING_EPARTMENT_2
     *
     * @return the value of gs_yanhui_reservation.ENGINEERING_EPARTMENT_2
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getEngineeringEpartment2() {
        return engineeringEpartment2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.ENGINEERING_EPARTMENT_2
     *
     * @param engineeringEpartment2 the value for gs_yanhui_reservation.ENGINEERING_EPARTMENT_2
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setEngineeringEpartment2(String engineeringEpartment2) {
        this.engineeringEpartment2 = engineeringEpartment2 == null ? null : engineeringEpartment2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.SECURITY_EPARTMENT_1
     *
     * @return the value of gs_yanhui_reservation.SECURITY_EPARTMENT_1
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getSecurityEpartment1() {
        return securityEpartment1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.SECURITY_EPARTMENT_1
     *
     * @param securityEpartment1 the value for gs_yanhui_reservation.SECURITY_EPARTMENT_1
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setSecurityEpartment1(String securityEpartment1) {
        this.securityEpartment1 = securityEpartment1 == null ? null : securityEpartment1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.SECURITY_EPARTMENT_2
     *
     * @return the value of gs_yanhui_reservation.SECURITY_EPARTMENT_2
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getSecurityEpartment2() {
        return securityEpartment2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.SECURITY_EPARTMENT_2
     *
     * @param securityEpartment2 the value for gs_yanhui_reservation.SECURITY_EPARTMENT_2
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setSecurityEpartment2(String securityEpartment2) {
        this.securityEpartment2 = securityEpartment2 == null ? null : securityEpartment2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.FINANCE_EPARTMENT_1
     *
     * @return the value of gs_yanhui_reservation.FINANCE_EPARTMENT_1
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getFinanceEpartment1() {
        return financeEpartment1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.FINANCE_EPARTMENT_1
     *
     * @param financeEpartment1 the value for gs_yanhui_reservation.FINANCE_EPARTMENT_1
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setFinanceEpartment1(String financeEpartment1) {
        this.financeEpartment1 = financeEpartment1 == null ? null : financeEpartment1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.FINANCE_EPARTMENT_2
     *
     * @return the value of gs_yanhui_reservation.FINANCE_EPARTMENT_2
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getFinanceEpartment2() {
        return financeEpartment2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.FINANCE_EPARTMENT_2
     *
     * @param financeEpartment2 the value for gs_yanhui_reservation.FINANCE_EPARTMENT_2
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setFinanceEpartment2(String financeEpartment2) {
        this.financeEpartment2 = financeEpartment2 == null ? null : financeEpartment2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.RECEPTION_1
     *
     * @return the value of gs_yanhui_reservation.RECEPTION_1
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getReception1() {
        return reception1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.RECEPTION_1
     *
     * @param reception1 the value for gs_yanhui_reservation.RECEPTION_1
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setReception1(String reception1) {
        this.reception1 = reception1 == null ? null : reception1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.RECEPTION_2
     *
     * @return the value of gs_yanhui_reservation.RECEPTION_2
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getReception2() {
        return reception2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.RECEPTION_2
     *
     * @param reception2 the value for gs_yanhui_reservation.RECEPTION_2
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setReception2(String reception2) {
        this.reception2 = reception2 == null ? null : reception2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.KEEPING_DPARTMENT_1
     *
     * @return the value of gs_yanhui_reservation.KEEPING_DPARTMENT_1
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getKeepingDpartment1() {
        return keepingDpartment1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.KEEPING_DPARTMENT_1
     *
     * @param keepingDpartment1 the value for gs_yanhui_reservation.KEEPING_DPARTMENT_1
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setKeepingDpartment1(String keepingDpartment1) {
        this.keepingDpartment1 = keepingDpartment1 == null ? null : keepingDpartment1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.KEEPING_DPARTMENT_2
     *
     * @return the value of gs_yanhui_reservation.KEEPING_DPARTMENT_2
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getKeepingDpartment2() {
        return keepingDpartment2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.KEEPING_DPARTMENT_2
     *
     * @param keepingDpartment2 the value for gs_yanhui_reservation.KEEPING_DPARTMENT_2
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setKeepingDpartment2(String keepingDpartment2) {
        this.keepingDpartment2 = keepingDpartment2 == null ? null : keepingDpartment2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.REMARKS
     *
     * @return the value of gs_yanhui_reservation.REMARKS
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.REMARKS
     *
     * @param remarks the value for gs_yanhui_reservation.REMARKS
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gs_yanhui_reservation.STATE
     *
     * @return the value of gs_yanhui_reservation.STATE
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gs_yanhui_reservation.STATE
     *
     * @param state the value for gs_yanhui_reservation.STATE
     *
     * @mbggenerated Fri Nov 17 10:34:22 CST 2017
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

}
